export const db = [
	{	
		id: 1,
		question: "Мне следовало сделать это вчера.",
		answer: "I should have done it yesterday",
		tag: "",
		difficulty: "",
	},
	{	
		id: 2,
		question: "Тебе следовало пойти туда.",
		answer: "You should have gone there.",
		tag: "",
		difficulty: "",
	},
	{	
		id: 3,
		question: "Тебе следовало принять его предложение.",
		answer: "You should have taken his offer.",
		tag: "",
		difficulty: "",
	},
	{	
		id: 4,
		question: "Мне бы стоило последовать его совету.",
		answer: "I should have followed his advice.",
		tag: "",
		difficulty: "",
	},
	{	
		id: 5,
		question: "Мне бы стоило послушать его.",
		answer: "I should have listened to him",
		tag: "",
		difficulty: "",
	},
	{	
		id: 6,
		question: "Мне следовало понять это намного ранее.",
		answer: "I should have understood it much earlier.",
		tag: "",
		difficulty: "",
	},
	{	
		id: 7,
		question: "Тебе следовало купить ту квартиру.",
		answer: "You should have bought that flat.",
		tag: "",
		difficulty: "",
	},
	{	
		id: 8,
		question: "Тебе следовало пойти туда с ней.",
		answer: "You should have gone there with her.",
		tag: "",
		difficulty: "",
	},
	{	
		id: 9,
		question: "Им следовало начать изучать английский раньше.",
		answer: "They should have started learning English earlier.",
		tag: "",
		difficulty: "",
	},
]